version: '3'
services:
  app:
    image: node:alpine
    ports:
      - 8080:8080
    volumes:
      - .:/home/node/app
    working_dir: /home/node/app
    command: yarn start:dev

  database:
    image: mongo:4.4.8
